### ISSUE TITLE
Getting lowercase char input

### ISSUE THREAD

**Issue by ajusa** [johnnovak/illwill#2]
Pretty much the title. I am trying to make a simple text editor using illwill, but based on the given example code the getKey() method returns a Key type, which doesn't seem to support lowercase characters. When I tried printing out keycodes it only printed the uppercase representation, such as "a" -> "A"

Also, if you could give any tips towards creating a text input in illwill, I would really appreciate it :smile:

**Comment by SolitudeSF** [comment]
they are lowercase, its just string representation that is uppercase. for *uppercase* chars, you query shifted keys https://github.com/johnnovak/illwill/blob/master/illwill.nim#L132

**Comment by ajusa** [comment]
Alright thanks! I scrolled right past that code when I was glancing through it.
