### ISSUE TITLE
Question: how to get status of modifier keys?

### ISSUE THREAD

**Issue by matkuki** [johnnovak/illwill#22]
Hi.

Is there a way to get the status of `Ctrl / Shift / Alt` keys, without using `getMouse` procedure?
`getMouse` only returns on a mouse event so it is not usable for key events.
I'm trying to get combinations like `Ctrl+Left/Right` and `Ctrl+Plus/Minus`

Thanks

**Comment by matkuki** [comment]
Found that adding raw combinations to `keySequences` in line `570` can be used to add some combinations,
but some combinations do not seem to register, like `Ctrl+Plus/Minus`.
Any ideas?

**Comment by johnnovak** [comment]
I don't think that's possible in a cross platform way. I think we could just use a subset that is supported in *nix terminal emulators. So certain Ctrl+<key> sequences, but not all of them. Similarly to what terminal based program like Vim support.
