### ISSUE TITLE
Can't get Ctrl-J

### ISSUE THREAD

**Issue by fox0430** [johnnovak/illwill#30]
I used `getKey` to press` Ctrl-J` but it's `Enter`. Is it only my environment? Do you know anything?

OS: Arch Linux
Terminal: Urxvt & Alacritty
Nim: v1.6.6

Code:
```nim
import std/os
import pkg/illwill

illwillInit()

while true:
  let key = getKey()
  if key != None:
    echo key
    echo int(key)
  sleep 20
```

Start this program and press `Ctrl-J`
```
Enter
13
```

In addition, I can get it normally with `terminal.getch`.

```nim
import std/terminal

let key = getch()
echo int(key)
```
Start this program and press `Ctrl-J`
```
10
```

**Comment by johnnovak** [comment]
Terminal issue, closing.

https://www.reddit.com/r/programming/comments/7qxgy/real_programmers_use_ctrlj_instead_of_enter_key/
