### ISSUE TITLE
Rollback nim version to 1.6.10

### ISSUE THREAD

**Issue by inv2004** [johnnovak/illwill#39]
Is it possible to rollback nim's minimal version to 1.6.10 ?

I have ttop tool (https://github.com/inv2004/ttop) which has your library in deps, but arch distro contains 1.6.10 only in extra repo => no one can install it via arch's yay

**Comment by johnnovak** [comment]
Nice monitoring tool @inv2004, glad to see illwill being put to good use! 🎉 

I've just released v0.3.2 which rolls back to Nim 1.6.10 as the minimum requirement.
